language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk8

before_install:
  - echo "package com.admin.tafmetar.view;
            public interface Info {
              String token = new String();
            }" > src/main/java/com/admin/tafmetar/view/Info.java
script:
  - ./gradlew assemble
